"""empty message

Revision ID: b30039801c85
Revises: da7e0f4f836c
Create Date: 2017-08-31 09:16:09.458616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b30039801c85'
down_revision = 'da7e0f4f836c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=80), nullable=False))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###
