"""empty message

Revision ID: ca28e7c29945
Revises: b30039801c85
Create Date: 2017-09-01 10:18:06.475569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca28e7c29945'
down_revision = 'b30039801c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Department', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=30), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'name')
    op.drop_column('users', 'Department')
    # ### end Alembic commands ###
