"""empty message

Revision ID: da7e0f4f836c
Revises: 2779e97d6308
Create Date: 2017-08-30 16:20:24.640314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7e0f4f836c'
down_revision = '2779e97d6308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
