"""empty message

Revision ID: ede061b1ac10
Revises: ca28e7c29945
Create Date: 2017-09-01 10:46:32.903527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ede061b1ac10'
down_revision = 'ca28e7c29945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=30), nullable=True))
    op.drop_column('users', 'Department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Department', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
